#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

VERSION=1.0

VERBOSE=0
RECURSIVE=0
NOACTION=0
FLAC_LEVEL=5 # Default FLAC compression level

CWD=$(pwd)
SELF="$(readlink -f "$0")"
OPTS=$(getopt -o Vvhrn012345678 \
              -l version,verbose,help,recursive,no-action,fast,best \
              -n reflac -- "$@")

eval set -- "$OPTS"

usage()
{
    cat <<EOF
‘reflac’ recompresses FLAC files while maintaining tags and file names.

Usage: reflac [OPTION]... [--] DIRECTORY...

 -h --help       Displays this help text
 -V --version    Displays the version of this program
 -v --verbose    Increases the verbosity.  Use once to display the FLACs
                 currently being processed, use twice for the full ‘flac’
                 output.
 -r --recursive  Recurse into directories.
 -n --no-action  Do not recompress.  With --verbose, displays a list of
                 files that would be processed.
 -0 --fast       Use the fastest, but worst, compression possible.
 -1..-7          Adjust FLAC compresion between these standard ranges.
                 The default is -5, the same as for flac itself.
 -8 --best       Use the slowest, but best, compression possible.

DIRECTORY should point ‘reflac’ to somewhere that contains *.flac
files. Optionally terminate the argument list with -- so that any
possible directory names don't get misinterpreted as arguments.
EOF

    exit 0
}

recompress()
{
    for flac in *.flac; do
        if [ $VERBOSE -eq 1 ]; then
            echo "  $flac"
        fi

        if [ $NOACTION -eq 0 ]; then
            metaflac --no-utf8-convert \
                     --export-tags-to="$(basename -s flac -- "$flac")tag" \
                     -- "$flac"

            if [ $VERBOSE -gt 1 ]; then
                flac --delete-input-file -d -- "$flac"
                flac --delete-input-file -$FLAC_LEVEL -- \
                     "$(basename -s flac -- "$flac")wav"
            else
                flac -s --delete-input-file -d -- "$flac"
                flac -s --delete-input-file -$FLAC_LEVEL -- \
                     "$(basename -s flac -- "$flac")wav"
            fi

            metaflac --no-utf8-convert \
                     --import-tags-from="$(basename -s flac -- "$flac")tag" \
                     -- "$flac"
            rm -f -- "$(basename -s flac -- "$flac")tag"
        fi
    done
}

while true ; do
    case "$1" in
        -v|--verbose)
            VERBOSE=$((VERBOSE+1))
            shift ;;
        -r|--recursive)
            RECURSIVE=1
            shift ;;
        -0|-1|-2|-3|-4|-5|-6|-7|-8)
            FLAC_LEVEL=${1#-}
            shift ;;
        --fast)
            FLAC_LEVEL=0
            shift ;;
        --best)
            FLAC_LEVEL=8
            shift ;;
        -n|--no-action)
            NOACTION=1
            shift ;;
        -V|--version)
            echo "reflac version $VERSION"
            exit 0 ;;
        -h|--help)
            usage ;;
        --) shift; break ;;
        *) echo "$0: This should never happen!" >&2; exit 1 ;;
    esac
done

if [ -z "$@" ]; then
    usage
fi

if [ $VERBOSE -eq 0 ] && [ $NOACTION -eq 1 ]; then
    exit 0
fi

for dir do
    if [ $RECURSIVE -eq 1 ] && [ $NOACTION -eq 1 ]; then
        find "$dir" -type d -exec "$SELF" -nv {} \;
    elif [ $RECURSIVE -eq 1 ]; then
        if [ $VERBOSE -eq 1 ]; then
            find "$dir" -type d -exec "$SELF" -v -"$FLAC_LEVEL" {} \;
        elif [ $VERBOSE -ge 2 ]; then
            find "$dir" -type d -exec "$SELF" -vv -"$FLAC_LEVEL" {} \;
        else
            find "$dir" -type d -exec "$SELF" -"$FLAC_LEVEL" {} \;
        fi
    else
        cd -- "$dir"
        if [ $VERBOSE -gt 0 ]; then echo "$dir"; fi
        if [ ! -z "$(ls -- *.flac 2>/dev/null)" ]; then
            recompress
        fi
        cd "$CWD"
    fi
done
